# Numpy
## Part 1: Basic Numpy array
##### 1. Defining Arrays
##### 2. Printing array
Through printing & looping
##### 3. Accessing element in array
##### 4. Indexing/Slicing elements in array
##### 5. NumPy Ndarray Properties
##### 6. NumPy Constants

In [1]:
import numpy as np

## 1. Defining arrays

In [2]:
# Defining arrays
array_1d = np.array([1, 2, 3], np.int16)  # 1D array of 16-bit int type
array_2d = np.array([[1, 2, 3], [4, 5, 6]], np.int16)   # 2D array of 16-bit int type
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],[[0, -1, -2], [-3, -4, -5]]], np.int16)   # 3D array of 16-bit int type 

## 2. Printing array

In [3]:
# Printing Array
print("\n1D Array: ", array_1d)  # [1 2 3]
print("\n2D Array: ", array_2d)  # [ [1 2 3] [4 5 6] ]
print("\n3D Array: ", array_3d)  # [ [ [1 2 3][ 4 5 6] ]  [ [0 -1 -2][-3 -4 -5] ] ] 

# # Print array in loop
[item for item in array_1d]  # 1, 2, 3,
[[item for item in subarray] for subarray in array_2d] # 1, 2, 3, 4, 5, 6,
[[[item for item in array1d] for array1d in array2d] for array2d in array_3d]  # 1, 2, 3, 4, 5, 6, 0, -1, -2, -3, -4, -5,


1D Array:  [1 2 3]

2D Array:  [[1 2 3]
 [4 5 6]]

3D Array:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4 -5]]]


[[[1, 2, 3], [4, 5, 6]], [[0, -1, -2], [-3, -4, -5]]]

## 3. Accessing element in array

In [4]:
# Accessing element in array
print(array_1d[0])        # 1 1st ele
print(array_1d[-1])       # 3 last ele
print(array_2d[0][1])     # 2 row=0, col=1
print(array_3d[0][1][2])  # 6 row=0, col=1, 3rd ele

1
3
2
6


## 4. Indexing/Slicing elements in array

In [5]:
# Slicing/indexing elements in array

# 1d indexing
print(array_1d[:2])  # [1 2]
print(array_1d[:])   # [1 2 3]

# 2d Indexing
print(array_2d[0, :]) # row=0, col=-1 > [1 2 3]

# 3d indexing
print(array_3d[:, :, 0])   # row=-1, col=-1, ele= 0th > [[ 1  4][ 0 -3]]

[1 2]
[1 2 3]
[1 2 3]
[[ 1  4]
 [ 0 -3]]


In [6]:
# Numpy array obj type
print(type(array_1d))

<class 'numpy.ndarray'>


##  5. NumPy Ndarray Properties

print(array_3d.shape)        # array shape > (2, 2, 3)
print(array_3d.ndim)         # no. of dimension > 3
print(array_3d.dtype)        # np.array type > int16
print(array_3d.size)         # total elements in array > 12
print(array_3d.nbytes)       # 8x2(int16) x 12 = 24 bytes

In [7]:
# Transpose of matrix
print(array_2d)
print()
print(array_2d.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


## 6. NumPy Constants

In [8]:
print(np.inf)     # +ve infinity
print(np.nan)     # not a number
print(np.NINF)    # -ve infinity
print(np.NZERO)   # -ve zero
print(np.PZERO)   # +ve zero
print(np.e)       # natutral logarithm > 2.718281828459045
print(np.euler_gamma)  # 0.5772156649015329
print(np.pi)      # pi 3.141592653589793

inf
nan
-inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793


In [9]:
# np.arange() > [0 1 2 3 4]
arange = np.arange(5)
print(arange)

[0 1 2 3 4]


In [10]:
# np.linespace() > [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
linespace = np.linspace(0, 10, 11)
print(linespace)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [11]:
# np.geimsapce()  > values from 0.1 to 1000 contain in array of size of 11 
y = np.geomspace(0.1, 1000, 11)
print(y)

[1.00000000e-01 2.51188643e-01 6.30957344e-01 1.58489319e+00
 3.98107171e+00 1.00000000e+01 2.51188643e+01 6.30957344e+01
 1.58489319e+02 3.98107171e+02 1.00000000e+03]


In [12]:
# logspace() > 0.1 to 1 contain in array of size of 11 
y = np.logspace(0.1, 1, 11)
print(y)

[ 1.25892541  1.54881662  1.90546072  2.34422882  2.8840315   3.54813389
  4.36515832  5.37031796  6.60693448  8.12830516 10.        ]
