## Array Manipulation Routines
Functions are: 
1. np.ravel()<br />
2. np.flatten()/flatten("C") & np.flatten("F")<br />
3. np.stack(), np.dstack(), np.hstack() & np.vstack()<br />
4. np.split(), np.dsplit(), np.hsplit() & np.vsplit()<br />
5. np.flip(), np.fliplr() & np.flipud()<br />
6. np.roll()<br />
7. np.rot90()<br />

In [1]:
import numpy as np
x = np.arange(6)      # [0 1 2 3 4 5]
y = x.reshape((3, 2)) # row=3, col=2
print(y.shape)        # (3, 2)
print(y)

(3, 2)
[[0 1]
 [2 3]
 [4 5]]


In [2]:
# np.ravel() > To convert dimensional array to linear array
ravel = np.ravel(y)
print(ravel)

[0 1 2 3 4 5]


In [3]:
# np.flatten() > To convert dimensional array to linear array 
## Coulmn wise
flatten = y.flatten()       # Col wise: [0 1 2 3 4 5]
print(flatten)

flatten_C = y.flatten('C')  # Col wise: [0 1 2 3 4 5]
print(flatten_C)

## Row wise
flatten_F = y.flatten('F')  # row wise: [0 2 4 1 3 5]
print(flatten_F)

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 2 4 1 3 5]


In [4]:
x = np.array([1, 2, 3], dtype = np.uint8)
y = np.array([4, 5, 6], dtype = np.uint8)

print(x.dtype)
print(x)
print(y)

uint8
[1 2 3]
[4 5 6]


In [5]:
# np.stack()/np.dstack() > combine two arrays in one 
z = np.stack((x, y))             # [[1 2 3]
                                 #  [4 5 6]]
print(z)

z = np.stack((x, y), axis = 0 )  # axis=0 > [[1 2 3]
                                 #          [4 5 6]]
print(z)

z = np.stack((x, y), axis = -1 ) # axis=-1 > [[1 4]
                                 #            [2 5]
                                 #            [3 6]]
print(z)

z = np.stack((x, y), axis = 1 )  # axis=-1 > [[1 4]
                                 #            [2 5]
                                 #            [3 6]]
print(z)

z = np.dstack((x, y))            # [[[1 4]
                                 #   [2 5]
                                 #   [3 6]]]
print(z)

z = np.hstack((x, y))            # [1 2 3 4 5 6]
print(z)

z = np.vstack((x, y))            # [[1 2 3]
                                 #  [4 5 6]]
print(z)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[[1 4]
  [2 5]
  [3 6]]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


## np.split()

In [6]:
a, b, c = np.split(x,  # [1 2 3]
                   3)  # split into 3
print(a, b, c)         # [1] [2] [3]

[1] [2] [3]


In [7]:
x = np.random.rand(4, 4, 4)
x

array([[[0.8541787 , 0.95817299, 0.11092703, 0.90230796],
        [0.50226783, 0.32481451, 0.37543635, 0.2307954 ],
        [0.25186099, 0.54422933, 0.9011475 , 0.28261784],
        [0.20618826, 0.54503747, 0.36584466, 0.80442579]],

       [[0.99714308, 0.81719727, 0.17737302, 0.06525877],
        [0.01500599, 0.22670109, 0.01106125, 0.42209787],
        [0.30184581, 0.92231715, 0.36480684, 0.45107646],
        [0.52462818, 0.96867221, 0.80055663, 0.7049133 ]],

       [[0.57872717, 0.85529725, 0.28583246, 0.85765012],
        [0.10978369, 0.68599992, 0.56733679, 0.17915801],
        [0.6832516 , 0.22851328, 0.64982675, 0.37402114],
        [0.86189587, 0.36155383, 0.54626441, 0.7148616 ]],

       [[0.19792075, 0.88830444, 0.36541298, 0.7126212 ],
        [0.62587055, 0.10069366, 0.11956534, 0.28347802],
        [0.11780144, 0.56065292, 0.35162808, 0.41615162],
        [0.21301364, 0.68178097, 0.46357436, 0.61059641]]])

In [8]:
y, z = np.dsplit(x, 2)
print(y, z)

[[[0.8541787  0.95817299]
  [0.50226783 0.32481451]
  [0.25186099 0.54422933]
  [0.20618826 0.54503747]]

 [[0.99714308 0.81719727]
  [0.01500599 0.22670109]
  [0.30184581 0.92231715]
  [0.52462818 0.96867221]]

 [[0.57872717 0.85529725]
  [0.10978369 0.68599992]
  [0.6832516  0.22851328]
  [0.86189587 0.36155383]]

 [[0.19792075 0.88830444]
  [0.62587055 0.10069366]
  [0.11780144 0.56065292]
  [0.21301364 0.68178097]]] [[[0.11092703 0.90230796]
  [0.37543635 0.2307954 ]
  [0.9011475  0.28261784]
  [0.36584466 0.80442579]]

 [[0.17737302 0.06525877]
  [0.01106125 0.42209787]
  [0.36480684 0.45107646]
  [0.80055663 0.7049133 ]]

 [[0.28583246 0.85765012]
  [0.56733679 0.17915801]
  [0.64982675 0.37402114]
  [0.54626441 0.7148616 ]]

 [[0.36541298 0.7126212 ]
  [0.11956534 0.28347802]
  [0.35162808 0.41615162]
  [0.46357436 0.61059641]]]


In [9]:
y, z = np.hsplit(x, 2)
print(y, z)

[[[0.8541787  0.95817299 0.11092703 0.90230796]
  [0.50226783 0.32481451 0.37543635 0.2307954 ]]

 [[0.99714308 0.81719727 0.17737302 0.06525877]
  [0.01500599 0.22670109 0.01106125 0.42209787]]

 [[0.57872717 0.85529725 0.28583246 0.85765012]
  [0.10978369 0.68599992 0.56733679 0.17915801]]

 [[0.19792075 0.88830444 0.36541298 0.7126212 ]
  [0.62587055 0.10069366 0.11956534 0.28347802]]] [[[0.25186099 0.54422933 0.9011475  0.28261784]
  [0.20618826 0.54503747 0.36584466 0.80442579]]

 [[0.30184581 0.92231715 0.36480684 0.45107646]
  [0.52462818 0.96867221 0.80055663 0.7049133 ]]

 [[0.6832516  0.22851328 0.64982675 0.37402114]
  [0.86189587 0.36155383 0.54626441 0.7148616 ]]

 [[0.11780144 0.56065292 0.35162808 0.41615162]
  [0.21301364 0.68178097 0.46357436 0.61059641]]]


In [10]:
y, z = np.vsplit(x, 2)
print(y, z)

[[[0.8541787  0.95817299 0.11092703 0.90230796]
  [0.50226783 0.32481451 0.37543635 0.2307954 ]
  [0.25186099 0.54422933 0.9011475  0.28261784]
  [0.20618826 0.54503747 0.36584466 0.80442579]]

 [[0.99714308 0.81719727 0.17737302 0.06525877]
  [0.01500599 0.22670109 0.01106125 0.42209787]
  [0.30184581 0.92231715 0.36480684 0.45107646]
  [0.52462818 0.96867221 0.80055663 0.7049133 ]]] [[[0.57872717 0.85529725 0.28583246 0.85765012]
  [0.10978369 0.68599992 0.56733679 0.17915801]
  [0.6832516  0.22851328 0.64982675 0.37402114]
  [0.86189587 0.36155383 0.54626441 0.7148616 ]]

 [[0.19792075 0.88830444 0.36541298 0.7126212 ]
  [0.62587055 0.10069366 0.11956534 0.28347802]
  [0.11780144 0.56065292 0.35162808 0.41615162]
  [0.21301364 0.68178097 0.46357436 0.61059641]]]


In [11]:
# np.flip() >  To rotate
x = np.arange(16).reshape(4, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [12]:
y = np.flip(x, axis = 1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [13]:
y = np.flip(x, axis = 0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [14]:
y = np.flip(x, axis = -1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [15]:
y = np.fliplr(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [16]:
y = np.flipud(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [17]:
# np.roll() > 1st 8 elements to last & last 8 elements to 1st place
y = np.roll(x, 8)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [18]:
# Rotate anti-clockwise 90 degree
y = np.rot90(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
