# Dot Product

In [1]:
import numpy as np

print(np.dot(10, 5))

50


In [2]:
a = np.array([2, 4], np.uint8)
b = np.array([5, 6], np.uint8)

print(np.dot(a, b))  # (2*5)+(4*6)=34

34


In [3]:
a = np.array([[2, 4], [5, 8]], np.uint8)
b = np.array([[5, 6], [9, 3]], np.uint8)

print(np.dot(a, b))

[[46 24]
 [97 54]]


In [4]:
a = np.random.rand(10, 5)
b = np.random.rand(5, 2)
c = np.random.rand(2, 3)
d = np.random.rand(3, 4)

e = np.linalg.multi_dot([a, b, c, d])
print(e)


[[1.4962986  1.11243145 1.44220732 1.42729872]
 [1.30839189 0.96229936 1.25116587 1.2734976 ]
 [1.55745529 1.14211217 1.4861297  1.52413464]
 [0.81569894 0.58887072 0.76949526 0.82092097]
 [0.89007817 0.66724691 0.86314868 0.83558762]
 [1.29776294 0.96003686 1.24628821 1.24960512]
 [0.61293932 0.45889774 0.59383125 0.57685917]
 [0.5847196  0.43138805 0.56041771 0.56586475]
 [1.12790912 0.84503366 1.09330516 1.06008565]
 [0.84353899 0.61999681 0.80625307 0.82204537]]


# Vector Dot Product

In [5]:
a = np.array ([1, 2])
b = np.array ([3, 4])

print(np.vdot(a, b))

11


In [6]:
a = np.array ([1 + 5j, 2 + 3j])
b = np.array ([3 + 2j, 4 + 7j])

print(np.vdot(a, b))

(42-11j)


In [7]:
print(np.vdot(b, a))

(42+11j)


# Inner Product

In [8]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([0, 1, 0, 1, 0, 1])

print(np.inner(a, b))

12


In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[0, 1, 0], [1, 0, 1]])

print(np.inner(a, b))

[[ 2  4]
 [ 5 10]]


# QR Decomposition

In [10]:
a = np.random.rand(3, 3)
print(a)

[[0.57820341 0.29770922 0.97786366]
 [0.71101691 0.7210673  0.71048506]
 [0.16380876 0.31116214 0.95699846]]


In [11]:
q, r = np.linalg.qr(a)
print('q = ', q, '\n\nr = ', r, '\n')

print(np.dot(q, r))

q =  [[-0.62107903  0.67989133  0.38988282]
 [-0.76374108 -0.41334228 -0.49583034]
 [-0.1759557  -0.60571935  0.77597916]] 

r =  [[-0.93096591 -0.79036042 -1.31834656]
 [ 0.         -0.28411461 -0.20850497]
 [ 0.          0.          0.77158306]] 

[[0.57820341 0.29770922 0.97786366]
 [0.71101691 0.7210673  0.71048506]
 [0.16380876 0.31116214 0.95699846]]


# Determinant and Solving Linear Equations

In [12]:
a = np.array([[5, 6], [3, 4]])

print(np.linalg.det(a))

2.0000000000000013


In [13]:
a = np.array([[2, 1, -3 ], [4, -2, 1], [3, 5, -2]], np.int16)
b = np.array([-4, 9, 5], np.int16)

# ax = b

x = np.linalg.solve(a, b)
print(x)

[2. 1. 3.]
