# Numpy

In [1]:
import numpy as np

## 1. Defining array, Access element  of array & Slicing of array 

In [24]:
# Defining Array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],[[0, -1, -2], [-3, -4, -5]]], np.int16)   # 3D array of 16-bit int type

# Printing
print("\n3D Array: ", array_3d)  # [ [ [1 2 3][ 4 5 6] ]  [ [0 -1 -2][-3 -4 -5] ] ] 

# Printing in loop
[[[item for item in array1d] for array1d in array2d] for array2d in array_3d]  # 1, 2, 3, 4, 5, 6, 0, -1, -2, -3, -4, -5,

print(type(lst))

<class 'list'>


In [18]:
# Accessing element
print(array_3d[0][1][2])  # 6 row=0, col=1, 3rd ele
# 3d indexing array
print(array_3d[:, :, 0])   # row=-1, col=-1, ele= 0th > [[ 1  4][ 0 -3]]

6
[[ 1  4]
 [ 0 -3]]


In [ ]:
arr = np.arange(50,70)

print(arr[4])
print(arr[8 : 20])
print(arr[-1])
print(sum(arr > 55))

In [37]:
print(arr + 100)
print(arr - 20)
print(arr * 2)
print(arr / 2)

[150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167
 168 169]
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138]
[25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5 30.  30.5 31.  31.5
 32.  32.5 33.  33.5 34.  34.5]


## 2. Numpy Constant

In [17]:
# Numpy Contant
print(np.inf)     # +ve infinity
print(np.nan)     # not a number
print(np.NINF)    # -ve infinity
print(np.NZERO)   # -ve zero
print(np.PZERO)   # +ve zero
print(np.e)       # natutral logarithm > 2.718281828459045
print(np.euler_gamma)  # 0.5772156649015329
print(np.pi)      # pi 3.141592653589793

inf
nan
-inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793


## 3. Numpy Manupulation

In [25]:
# 1. np.empty() function
empty = np.empty([3, 3], np.uint8) # Random Values in array
print(empty)

[[224 251  28]
 [ 64 188 127]
 [  0   0 224]]


In [30]:
# 2. np.eye function
eye_k_0 = 5 * np.eye(5, dtype=np.uint8, k=0)  # k = 0 (By default)
print(eye_k_0, "\n")

eye_k_1 = 2 / np.eye(5, dtype=np.uint8, k=1)  # k = 1
print(eye_k_1, "\n")

eye_k_minus_1 = 3 + np.eye(5, dtype=np.uint8, k=-1)  # K= -1
print(eye_k_minus_1, "\n")

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]] 

[[inf  2. inf inf inf]
 [inf inf  2. inf inf]
 [inf inf inf  2. inf]
 [inf inf inf inf  2.]
 [inf inf inf inf inf]] 

[[3 3 3 3 3]
 [4 3 3 3 3]
 [3 4 3 3 3]
 [3 3 4 3 3]
 [3 3 3 4 3]] 



/home/hamza/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


In [31]:
# 3. np.identity() function
identity = 3 * np.identity(5, dtype= np.uint8)
print(identity)

[[3 0 0 0 0]
 [0 3 0 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]]


In [5]:
np.zeros(shape=(4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
5 * np.ones(shape=(3, 5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [28]:
# 6. np.fill() function > Fill all indexes by value 
full_fill = np.full((3, 3, 3), dtype=np.int16, fill_value = 5)
print(full_fill)

[[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]


In [7]:
np.arange(-5, 10)
np.arange(-5, 10, 3)

array([-5, -2,  1,  4,  7])

In [8]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [49]:
x = np.arange(6)      # [0 1 2 3 4 5]
x.reshape((3, 2)) # row=3, col=2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [50]:
# np.ravel() > To convert dimensional array to linear array
np.ravel(x)

array([0, 1, 2, 3, 4, 5])

In [79]:
# np.unique() > return only unique values
np.unique(x.flatten())

array([-3.14159265,  3.14159265])

In [51]:
# np.flatten() > To convert dimensional array to linear array 
## Coulmn wise
flatten = x.flatten()       # Col wise: [0 1 2 3 4 5]
print(flatten)

flatten_C = x.flatten('C')  # Col wise: [0 1 2 3 4 5]
print(flatten_C)

## Row wise
flatten_F = x.flatten('F')  # row wise: [0 2 4 1 3 5]
print(flatten_F)

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [54]:
x = np.array([1, 2, 3], dtype = np.uint8)
y = np.array([4, 5, 6], dtype = np.uint8)

# np.stack()/np.dstack() > combine two arrays in one 
z = np.stack((x, y))             # [[1 2 3]
                                 #  [4 5 6]]
print(z)

z = np.stack((x, y), axis = 0 )  # axis=0 > [[1 2 3]
                                 #          [4 5 6]]
print(z)

z = np.stack((x, y), axis = -1 ) # axis=-1 > [[1 4]
                                 #            [2 5]
                                 #            [3 6]]
print(z)

z = np.stack((x, y), axis = 1 )  # axis=-1 > [[1 4]
                                 #            [2 5]
                                 #            [3 6]]
print(z)

z = np.dstack((x, y))            # [[[1 4]
                                 #   [2 5]
                                 #   [3 6]]]
print(z)

z = np.hstack((x, y))            # [1 2 3 4 5 6]
print(z)

z = np.vstack((x, y))            # [[1 2 3]
                                 #  [4 5 6]]
print(z)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[[1 4]
  [2 5]
  [3 6]]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [64]:
# np.split()
x = np.arange(15)
a, b, c = np.split(x,  # [1 2 3]
                   3)  # split into 3
print(a, b, c)         # [1] [2] [3]

x= np.array([[[1, 2, 3], [4, 5, 6]],[[0, -1, -2], [-3, -4, -5]]], np.int16)   # 3D array of 16-bit int type
# a, b = np.dsplit(x, 2)
print(a, b)

# a, b = np.hsplit(x, 2)
print(a, b)

# a, b = np.vsplit(x, 2)
print(a, b)

[0 1 2 3 4] [5 6 7 8 9] [10 11 12 13 14]


In [82]:
# np.sort()
data = np.array([[1, 2, 3],
                [3, 2, 1]])

# sort data row wise
print("Row: ", np.sort(data))
print("Row: ", np.sort(data, axis = -1))
print("Row: ", np.sort(data, axis = 1))

# sort data column wise
print("\nColumn: ", np.sort(data, axis = 0))

Row:  [[1 2 3]
 [1 2 3]]
Row:  [[1 2 3]
 [1 2 3]]
Row:  [[1 2 3]
 [1 2 3]]

Column:  [[1 2 1]
 [3 2 3]]


## 4. Random Routines

In [29]:
# np.random.randint() 
randint = np.random.randint( low = 0, high = 9, size = 10)  # item varies from 0 to 9 inside array of size 10
print(randint)

[1 8 4 7 6 7 0 3 3 5]


In [33]:
np.random.rand(2,3 , 6)

array([[[0.70920729, 0.87632473, 0.83716404, 0.82174875, 0.09363353,
         0.23883616],
        [0.76485185, 0.39236864, 0.59522167, 0.05024529, 0.17336632,
         0.91106043],
        [0.02156991, 0.18080991, 0.48868799, 0.15287406, 0.06432541,
         0.8022512 ]],

       [[0.8453662 , 0.41758623, 0.06255922, 0.64232419, 0.64321826,
         0.42185874],
        [0.40116969, 0.06062994, 0.37165858, 0.58675101, 0.1267905 ,
         0.47606142],
        [0.95438132, 0.25879152, 0.01930437, 0.85910944, 0.92266813,
         0.90524356]]])

In [35]:
mat = np.random.randn(4,5)
mat

array([[-0.70330751,  0.66135371, -0.69491636, -1.35494565, -2.09552667],
       [ 2.11603036, -0.28221679, -0.30250965,  0.22626125, -1.51998283],
       [-0.48912383,  0.32410279,  0.49808207, -0.3733867 ,  0.93219959],
       [-2.28214659,  0.99827435, -0.27335071,  0.95619846, -1.87100109]])

## 5. Properties

In [12]:
print(type(mat))
print(mat.size)
print(mat.shape)
print(mat.reshape(2,10).shape)
print(mat.dtype)

<class 'numpy.ndarray'>
20
(4, 5)
(2, 10)
float64


## 6. Bit Wise Operator

In [65]:
x = np.array([0, 1, 0, 1], np.uint8)
y = np.array([0, 0, 1, 1], np.uint8)

print(np.bitwise_and(x, y))
print(np.bitwise_or(x, y))
print(np.bitwise_xor(x, y))
print(np.bitwise_not(x))     # it is due to unit8

[0 0 0 1]
[0 1 1 1]
[0 1 1 0]
[255 254 255 254]


## 7. Statistical Function

In [68]:
a = np.random.randint(low = 0, high = 10, size = 10)
print("List: ", a)
print("Median: ", np.median(a))
print("Mean: ", np.mean(a))
print("Average: ", np.average(a))
print("Standard Deviation: ", np.std(a))
print("Variance: ", np.var(a))
print("Histogram: ", np.histogram(a))

List:  [0 9 9 9 0 8 8 0 5 1]
Median:  6.5
Mean:  4.9
Average:  4.9
Standard Deviation:  3.961060464067672
Variance:  15.690000000000001
Histogram:  (array([3, 1, 0, 0, 0, 1, 0, 0, 2, 3]), array([0. , 0.9, 1.8, 2.7, 3.6, 4.5, 5.4, 6.3, 7.2, 8.1, 9. ]))


## 8. Trignomentric Functions

In [72]:
x = np.linspace(-np.pi, np.pi, 2)

print("Sin: ", np.sin(x))
print("Cos :", np.cos(x))
print("Tan :", np.tan(x))
print("Sinh :", np.sinh(x))
print("Cosh :", np.cosh(x))
print("Tanh :", np.tanh(x))
print("Exponential :", np.exp(x))
print("Log :", np.log(x))

Sin:  [-1.2246468e-16  1.2246468e-16]
Cos : [-1. -1.]
Tan : [ 1.2246468e-16 -1.2246468e-16]
Sinh : [-11.54873936  11.54873936]
Cosh : [11.59195328 11.59195328]
Tanh : [-0.99627208  0.99627208]
Exponential : [ 0.04321392 23.14069263]
Log : [       nan 1.14472989]


/home/hamza/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in log
  # Remove the CWD from sys.path while we load stuff.


## 9. Numpy writing and reading files

### save & load .npy file

In [ ]:
x = np.arange(100)
np.save('test.npy', x)

In [ ]:
data = np.load('test.npy')
print(data)

### Reading the data from a CSV file

In [ ]:
data = np.loadtxt('data.csv', delimiter=',',
                 skiprows=-1,
                 usecols=[1, 3]) 
print(data)